### ISSUE TITLE
Update needed on PDF documentation on OSIRIS

### ISSUE THREAD

**Issue by juguerin** [siric-osiris/OSIRIS#21]
@VincentLeTexier The PDF documentation of OSIRIS should be updated.
There are several gaps between the official items and the PDF document.

https://github.com/siric-osiris/OSIRIS/blob/master/documentation/ModeleCliniqueOSIRIS-english_version.pdf

Ex : items 10.1 and 10.2 ("Confirmation of diagnosis") are not existing.

**Comment by VincentLeTexier** [comment]
10.1 and 10.2 are the Analysis_Type and Analysis_Date.
