### ISSUE TITLE
Need information for OSIRIS_pivot_RadiomicsFeature.csv

### ISSUE THREAD

**Issue by MaelleBaillet5** [siric-osiris/OSIRIS#24]
The pivot file [OSIRIS_pivot_RadiomicsFeature.csv ](https://github.com/siric-osiris/OSIRIS/blob/MED-OSIRIS/pivot/OSIRIS_pivot_RadiomicsFeature.csv) contains many variables while there are only 3 in the pdf [ModeleRadiomique](https://github.com/siric-osiris/OSIRIS/blob/MED-OSIRIS/documentation/ModeleRadiomiqueOSIRIS.pdf).
Do these different variables correspond to the different features? If so, could we have a mapping table linking each feature to its IBSI standard (IBSI standard number or feature name in the nomenclature)?

**Comment by VincentLeTexier** [comment]
We have updated this file and added the IBSI codes.
