### ISSUE TITLE
MorphologyCode english Definition is in french

### ISSUE THREAD

**Issue by nriss** [siric-osiris/OSIRIS#3]
see https://github.com/siric-osiris/OSIRIS/wiki/TumorPathologyEvent_MorphologyCode 

Code international de la lésion / type histologique / morphologie de l'événement tumoral

Proposition:
`International code of lesion / histological type / morphology of the tumoral event`

**Comment by juguerin** [comment]
Thanks @nriss !
We updated the OSIRIS wiki based on your  suggestion.
